const fs=require('node:fs'),{validateBundle}=require('../lib/core');
const read=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const version=read('version.json');
const bundle={version,tokens:read('design/tokens.json'),countdown:read('config/countdown.json'),locales:{en:read('locales/en.json'),ko:read('locales/ko.json')},screens:Object.fromEntries(version.screenOrder.map(k=>[k,read('screens/'+k+'.json')]))};
validateBundle(bundle);
fs.writeFileSync('plugin/code.js','// Generated by npm run build; edit lib/core.js and plugin/renderer.js.\n'+fs.readFileSync('lib/core.js','utf8')+'\nconst BUNDLED='+JSON.stringify(bundle)+';\n'+fs.readFileSync('plugin/renderer.js','utf8'));
console.log('Built plugin with '+version.screenOrder.length+' screens and 2 locales.');
